% =======================================================================
% This script is used to test the function GMM which contain a Gaussian
% Mixture Model algorithm.
% The test data set was generated by fucntion GENERATEGD which contain
% three independent single Guassian Distribution. The parameters of each
% single Gaussian Distribution was predefined.
%
% Author:Hammer Zhang
% Time:2015-12-22
% =======================================================================

% 测试数据集是由三个二元高斯分布生成的N点数据
% 设置SDM 参数
% N:数据样本数量 D:数据维度,D = 2 K:混合高斯模型含有的独立高斯分布数
% Mu:1-by-D-by-K matrix
Mu1 = [1,2]; Mu2 = [8,1]; Mu3 = [7,5];
Mu =[Mu1,Mu2,Mu3];
Mu = reshape(Mu,1,2,3);   

% Sigma:D-by-D-by-K matrix
Sigma1 = [1,0;0,2]; Sigma2 = [2,0;0,3]; Sigma3 = [1,0;0,4];
Sigma = [Sigma1,Sigma2,Sigma3];
Sigma = reshape(Sigma,2,2,3);

N = 1000;

% R: 样本数据集，N-by-D matrix
R = GenerateGD(Mu,Sigma,N);
% 绘图显示样本数据
figure;
plot(R(1:1000,1),R(1:1000,2),'bo');
hold on;
plot(R(1001:2000,1),R(1001:2000,2),'r+');
plot(R(2001:3000,1),R(2001:3000,2),'gx');

% 使用GMM对数据集分类
[pPi,pMu,pSigma,it] = GMM(R,3);









